# Air configuration file for live-reloading Go apps

# Project root directory (relative to .air.toml)
root = "."

# Directory where the binary will be built
tmp_dir = "tmp"

# Name of the temporary binary
bin = "tmp/synchme"

# Command to run the app
cmd = "make run"

# File extensions to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]

# Directories to ignore
exclude_dir = ["assets", "tmp", "vendor", ".git", ".devcontainer", "bin"]

# Logging settings
log_time = true
color = true

# Optional: delay before rebuilding after a file change (milliseconds)
# delay = 500
