// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorStatus_Status int32

const (
	ErrorStatus_SUCCESS ErrorStatus_Status = 0 // The request has been accepted
	ErrorStatus_FAILURE ErrorStatus_Status = 1 // The request has not been accepted
)

// Enum value maps for ErrorStatus_Status.
var (
	ErrorStatus_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	ErrorStatus_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x ErrorStatus_Status) Enum() *ErrorStatus_Status {
	p := new(ErrorStatus_Status)
	*p = x
	return p
}

func (x ErrorStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[0].Descriptor()
}

func (ErrorStatus_Status) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[0]
}

func (x ErrorStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorStatus_Status.Descriptor instead.
func (ErrorStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0, 0}
}

type ErrorStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ErrorStatus_Status     `protobuf:"varint,1,opt,name=status,proto3,enum=session.ErrorStatus_Status" json:"status,omitempty"` // The response status
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                  // An optional msg indicating the error reason
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorStatus) Reset() {
	*x = ErrorStatus{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatus) ProtoMessage() {}

func (x *ErrorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatus.ProtoReflect.Descriptor instead.
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorStatus) GetStatus() ErrorStatus_Status {
	if x != nil {
		return x.Status
	}
	return ErrorStatus_SUCCESS
}

func (x *ErrorStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Sent by the client requesting the Authorization token for synchronization
type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Unique ID for the client (client-side generation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *TokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Sent by the server when responding to the token request, once the authentication
// operation is successful
type TokenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                          // The authorization token used by the server
	ExpirationDate int64                  `protobuf:"varint,2,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"` // When the token will expire and a new one is required
	Status         *ErrorStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                        // The status of the response (OK/ERROR + optional reason)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenResponse) GetExpirationDate() int64 {
	if x != nil {
		return x.ExpirationDate
	}
	return 0
}

func (x *TokenResponse) GetStatus() *ErrorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Sent by the client when it connects after authentication
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Unique ID for the client (client-side generation)
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`                       // List of paths it wants to sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *HelloRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HelloRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// Sent by the server as response to the ClientHello message
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ErrorStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // The status of the response (OK/ERROR + optional reason)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *HelloResponse) GetStatus() *ErrorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// Sent periodically by the client to informs the server
// that the current client is alive and ready for reaching
// or pushing synchronization updates.
type HeartbeatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // The client ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // The timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatMsg) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HeartbeatMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Sent by the client to requests the name of all services
// registered to the server.
type ServicesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Services      []*ServicesResponse_Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"` // A list with all services
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesResponse) Reset() {
	*x = ServicesResponse{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse) ProtoMessage() {}

func (x *ServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse.ProtoReflect.Descriptor instead.
func (*ServicesResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

func (x *ServicesResponse) GetServices() []*ServicesResponse_Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServicesResponse_Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`          // The name of the service
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"` // If the service is required to work or not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesResponse_Service) Reset() {
	*x = ServicesResponse_Service{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesResponse_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse_Service) ProtoMessage() {}

func (x *ServicesResponse_Service) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse_Service.ProtoReflect.Descriptor instead.
func (*ServicesResponse_Service) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ServicesResponse_Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicesResponse_Service) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\asession\x1a\x1bgoogle/protobuf/empty.proto\"~\n" +
	"\vErrorStatus\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.session.ErrorStatus.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\"\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\"+\n" +
	"\fTokenRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"|\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12'\n" +
	"\x0fexpiration_date\x18\x02 \x01(\x03R\x0eexpirationDate\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x14.session.ErrorStatusR\x06status\"A\n" +
	"\fHelloRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"=\n" +
	"\rHelloResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.session.ErrorStatusR\x06status\"I\n" +
	"\fHeartbeatMsg\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x8c\x01\n" +
	"\x10ServicesResponse\x12=\n" +
	"\bservices\x18\x01 \x03(\v2!.session.ServicesResponse.ServiceR\bservices\x1a9\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired2\xfb\x01\n" +
	"\aSession\x12=\n" +
	"\fGetAuthToken\x12\x15.session.TokenRequest\x1a\x16.session.TokenResponse\x126\n" +
	"\x05Hello\x12\x15.session.HelloRequest\x1a\x16.session.HelloResponse\x12:\n" +
	"\tHeartbeat\x12\x15.session.HeartbeatMsg\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\bServices\x12\x16.google.protobuf.Empty\x1a\x19.session.ServicesResponseB3Z1github.com/synchme/internal/proto/session;sessionb\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_session_proto_goTypes = []any{
	(ErrorStatus_Status)(0),          // 0: session.ErrorStatus.Status
	(*ErrorStatus)(nil),              // 1: session.ErrorStatus
	(*TokenRequest)(nil),             // 2: session.TokenRequest
	(*TokenResponse)(nil),            // 3: session.TokenResponse
	(*HelloRequest)(nil),             // 4: session.HelloRequest
	(*HelloResponse)(nil),            // 5: session.HelloResponse
	(*HeartbeatMsg)(nil),             // 6: session.HeartbeatMsg
	(*ServicesResponse)(nil),         // 7: session.ServicesResponse
	(*ServicesResponse_Service)(nil), // 8: session.ServicesResponse.Service
	(*emptypb.Empty)(nil),            // 9: google.protobuf.Empty
}
var file_session_proto_depIdxs = []int32{
	0, // 0: session.ErrorStatus.status:type_name -> session.ErrorStatus.Status
	1, // 1: session.TokenResponse.status:type_name -> session.ErrorStatus
	1, // 2: session.HelloResponse.status:type_name -> session.ErrorStatus
	8, // 3: session.ServicesResponse.services:type_name -> session.ServicesResponse.Service
	2, // 4: session.Session.GetAuthToken:input_type -> session.TokenRequest
	4, // 5: session.Session.Hello:input_type -> session.HelloRequest
	6, // 6: session.Session.Heartbeat:input_type -> session.HeartbeatMsg
	9, // 7: session.Session.Services:input_type -> google.protobuf.Empty
	3, // 8: session.Session.GetAuthToken:output_type -> session.TokenResponse
	5, // 9: session.Session.Hello:output_type -> session.HelloResponse
	9, // 10: session.Session.Heartbeat:output_type -> google.protobuf.Empty
	7, // 11: session.Session.Services:output_type -> session.ServicesResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		EnumInfos:         file_session_proto_enumTypes,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
