// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloResponse_Status int32

const (
	HelloResponse_SUCCESS HelloResponse_Status = 0 // The request has been accepted
	HelloResponse_FAILURE HelloResponse_Status = 1 // The request has not been accepted
)

// Enum value maps for HelloResponse_Status.
var (
	HelloResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	HelloResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x HelloResponse_Status) Enum() *HelloResponse_Status {
	p := new(HelloResponse_Status)
	*p = x
	return p
}

func (x HelloResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelloResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[0].Descriptor()
}

func (HelloResponse_Status) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[0]
}

func (x HelloResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelloResponse_Status.Descriptor instead.
func (HelloResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1, 0}
}

// Sent by the client when it connects after authentication
type ClientHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                      // Unique ID for the client (client-side generation)
	SubscribedPaths []string               `protobuf:"bytes,2,rep,name=subscribed_paths,json=subscribedPaths,proto3" json:"subscribed_paths,omitempty"` // List of paths it wants to sync
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientHello) GetSubscribedPaths() []string {
	if x != nil {
		return x.SubscribedPaths
	}
	return nil
}

// Sent by the server as response to the ClientHello message
type HelloResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerNs        string                 `protobuf:"bytes,1,opt,name=server_ns,json=serverNs,proto3" json:"server_ns,omitempty"`                      // The server that responded to the request
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                      // Unique ID for the client (client-side generation)
	SubscribedPaths []string               `protobuf:"bytes,3,rep,name=subscribed_paths,json=subscribedPaths,proto3" json:"subscribed_paths,omitempty"` // List of paths actually assigned to the client
	Status          HelloResponse_Status   `protobuf:"varint,4,opt,name=status,proto3,enum=session.HelloResponse_Status" json:"status,omitempty"`       // The response status
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                          // An optional msg indicating the error reason
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetServerNs() string {
	if x != nil {
		return x.ServerNs
	}
	return ""
}

func (x *HelloResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HelloResponse) GetSubscribedPaths() []string {
	if x != nil {
		return x.SubscribedPaths
	}
	return nil
}

func (x *HelloResponse) GetStatus() HelloResponse_Status {
	if x != nil {
		return x.Status
	}
	return HelloResponse_SUCCESS
}

func (x *HelloResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Sent periodically by the client to informs the server
// that the current client is alive and ready for reaching
// or pushing synchronization updates.
type HeartbeatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // The client ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // The timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMsg) Reset() {
	*x = HeartbeatMsg{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMsg) ProtoMessage() {}

func (x *HeartbeatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMsg.ProtoReflect.Descriptor instead.
func (*HeartbeatMsg) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatMsg) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HeartbeatMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Sent by the client to requests the name of all services
// registered to the server.
type ServicesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Services      []*ServicesResponse_Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"` // A list with all services
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesResponse) Reset() {
	*x = ServicesResponse{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse) ProtoMessage() {}

func (x *ServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse.ProtoReflect.Descriptor instead.
func (*ServicesResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *ServicesResponse) GetServices() []*ServicesResponse_Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServicesResponse_Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`          // The name of the service
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"` // If the service is required to work or not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicesResponse_Service) Reset() {
	*x = ServicesResponse_Service{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicesResponse_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse_Service) ProtoMessage() {}

func (x *ServicesResponse_Service) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse_Service.ProtoReflect.Descriptor instead.
func (*ServicesResponse_Service) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ServicesResponse_Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicesResponse_Service) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\asession\x1a\x1bgoogle/protobuf/empty.proto\"U\n" +
	"\vClientHello\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12)\n" +
	"\x10subscribed_paths\x18\x02 \x03(\tR\x0fsubscribedPaths\"\xe7\x01\n" +
	"\rHelloResponse\x12\x1b\n" +
	"\tserver_ns\x18\x01 \x01(\tR\bserverNs\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12)\n" +
	"\x10subscribed_paths\x18\x03 \x03(\tR\x0fsubscribedPaths\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.session.HelloResponse.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\"\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\"I\n" +
	"\fHeartbeatMsg\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x8c\x01\n" +
	"\x10ServicesResponse\x12=\n" +
	"\bservices\x18\x01 \x03(\v2!.session.ServicesResponse.ServiceR\bservices\x1a9\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired2\xbb\x01\n" +
	"\aSession\x125\n" +
	"\x05Hello\x12\x14.session.ClientHello\x1a\x16.session.HelloResponse\x12:\n" +
	"\tHeartbeat\x12\x15.session.HeartbeatMsg\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\bServices\x12\x16.google.protobuf.Empty\x1a\x19.session.ServicesResponseB3Z1github.com/synchme/internal/proto/session;sessionb\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_session_proto_goTypes = []any{
	(HelloResponse_Status)(0),        // 0: session.HelloResponse.Status
	(*ClientHello)(nil),              // 1: session.ClientHello
	(*HelloResponse)(nil),            // 2: session.HelloResponse
	(*HeartbeatMsg)(nil),             // 3: session.HeartbeatMsg
	(*ServicesResponse)(nil),         // 4: session.ServicesResponse
	(*ServicesResponse_Service)(nil), // 5: session.ServicesResponse.Service
	(*emptypb.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_session_proto_depIdxs = []int32{
	0, // 0: session.HelloResponse.status:type_name -> session.HelloResponse.Status
	5, // 1: session.ServicesResponse.services:type_name -> session.ServicesResponse.Service
	1, // 2: session.Session.Hello:input_type -> session.ClientHello
	3, // 3: session.Session.Heartbeat:input_type -> session.HeartbeatMsg
	6, // 4: session.Session.Services:input_type -> google.protobuf.Empty
	2, // 5: session.Session.Hello:output_type -> session.HelloResponse
	6, // 6: session.Session.Heartbeat:output_type -> google.protobuf.Empty
	4, // 7: session.Session.Services:output_type -> session.ServicesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		EnumInfos:         file_session_proto_enumTypes,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
