name: Go Unit-test and linting

on:
  push:
    branches: [testing]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.25]

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      - name: Patch config for CI
        run: |
          sed -i 's|^paths = .*|paths = ["'"$(pwd)"'/test1"]|' test/configs/test_config.toml
          mkdir -p ./test1
          cat test/configs/test_config.toml

      # Run tests
      - name: Run tests
        run: go test ./... -v

      # Run linter
      - name: Run linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...
